services:
    auth:
        depends_on:
            graphql:
                condition: service_started
            postgres:
                condition: service_healthy
        environment:
            AUTH_ANONYMOUS_USERS_ENABLED: "false"
            AUTH_CLIENT_URL: http://localhost:3000
            AUTH_DISABLE_NEW_USERS: "false"
            AUTH_EMAIL_ENABLED: "false"
            AUTH_EMAIL_PASSWORDLESS_ENABLED: "false"
            AUTH_EMAIL_SIGNIN_EMAIL_VERIFIED_REQUIRED: "true"
            AUTH_GRAVATAR_ENABLED: "true"
            AUTH_HOST: 0.0.0.0
            AUTH_LOCALE_ALLOWED: en
            AUTH_LOCALE_DEFAULT: en
            AUTH_PASSWORD_HIBP_ENABLED: "false"
            AUTH_PASSWORD_MIN_LENGTH: "3"
            AUTH_PROVIDER_APPLE_ENABLED: "false"
            AUTH_PROVIDER_APPLE_SCOPE: name,email
            AUTH_PROVIDER_BITBUCKET_ENABLED: "false"
            AUTH_PROVIDER_FACEBOOK_ENABLED: "false"
            AUTH_PROVIDER_FACEBOOK_SCOPE: email,photos,displayName
            AUTH_PROVIDER_GITHUB_ENABLED: "false"
            AUTH_PROVIDER_GITHUB_SCOPE: user:email
            AUTH_PROVIDER_GITLAB_ENABLED: "false"
            AUTH_PROVIDER_GITLAB_SCOPE: read_user
            AUTH_PROVIDER_GOOGLE_ENABLED: "false"
            AUTH_PROVIDER_GOOGLE_SCOPE: email,profile
            AUTH_PROVIDER_LINKEDIN_ENABLED: "false"
            AUTH_PROVIDER_LINKEDIN_SCOPE: r_emailaddress,r_liteprofile
            AUTH_PROVIDER_SPOTIFY_ENABLED: "false"
            AUTH_PROVIDER_SPOTIFY_SCOPE: user-read-email,user-read-private
            AUTH_PROVIDER_STRAVA_ENABLED: "false"
            AUTH_PROVIDER_TWILIO_ENABLED: "false"
            AUTH_PROVIDER_TWITTER_ENABLED: "false"
            AUTH_PROVIDER_WINDOWS_LIVE_ENABLED: "false"
            AUTH_PROVIDER_WINDOWS_LIVE_SCOPE: wl.basic,wl.emails,wl.contacts_emails
            AUTH_SERVER_URL: http://localhost:1337/v1/auth
            AUTH_SMS_ENABLED: "false"
            AUTH_SMS_PASSWORDLESS_ENABLED: "false"
            AUTH_SMTP_HOST: mailhog
            AUTH_SMTP_PASS: password
            AUTH_SMTP_PORT: "1025"
            AUTH_SMTP_SECURE: "false"
            AUTH_SMTP_SENDER: hasura-auth@example.com
            AUTH_SMTP_USER: user
            AUTH_TOKEN_ACCESS_EXPIRES_IN: "900"
            AUTH_TOKEN_REFRESH_EXPIRES_IN: "43200"
            AUTH_USER_ALLOWED_ROLES: user,me
            AUTH_USER_DEFAULT_ALLOWED_ROLES: user,me
            AUTH_USER_DEFAULT_ROLE: user
            AUTH_USER_MFA_ENABLED: "false"
            AUTH_USER_MFA_ISSUER: nhost
            HASURA_GRAPHQL_ADMIN_SECRET: nhost-admin-secret
            HASURA_GRAPHQL_DATABASE_URL: postgres://nhost_auth_admin@postgres:5432/postgres
            HASURA_GRAPHQL_GRAPHQL_URL: http://graphql:8080/v1/graphql
            HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "0f987876650b4a085e64594fae9219e7781b17506bec02489ad061fba8cb22db"}'
            NHOST_ADMIN_SECRET: nhost-admin-secret
            NHOST_WEBHOOK_SECRET: nhost-webhook-secret
        expose:
            - "4000"
        extra_hosts:
            - host.docker.internal:host-gateway
        healthcheck:
            test:
                - CMD-SHELL
                - wget http://localhost:4000/healthz -q -O - > /dev/null 2>&1
            interval: 3s
            start_period: 5m0s
        image: nhost/hasura-auth:0.19.0
        labels:
            traefik.enable: "true"
            traefik.http.middlewares.strip-auth.stripprefix.prefixes: /v1/auth
            traefik.http.routers.auth.entrypoints: web
            traefik.http.routers.auth.middlewares: strip-auth@docker
            traefik.http.routers.auth.rule: PathPrefix(`/v1/auth`)
        restart: always
        volumes:
            - type: bind
              source: /home/alicia/Documents/rebound-chatbot/.nhost/custom
              target: /app/custom
            - type: bind
              source: /home/alicia/Documents/rebound-chatbot/nhost/emails
              target: /app/email-templates
    dashboard:
        environment:
            NEXT_PUBLIC_ENV: dev
            NEXT_PUBLIC_NHOST_HASURA_PORT: "9695"
            NEXT_PUBLIC_NHOST_LOCAL_BACKEND_PORT: "1337"
            NEXT_PUBLIC_NHOST_MIGRATIONS_PORT: "9693"
            NEXT_PUBLIC_NHOST_PLATFORM: "false"
            NEXT_TELEMETRY_DISABLED: "1"
        extra_hosts:
            - host.docker.internal:host-gateway
        image: nhost/dashboard:0.11.13
        ports:
            - mode: ingress
              target: 3000
              published: "3030"
              protocol: tcp
    functions:
        environment:
            NHOST_ADMIN_SECRET: nhost-admin-secret
            NHOST_AUTH_URL: http://traefik:1337/v1/auth
            NHOST_BACKEND_URL: http://traefik:1337
            NHOST_FUNCTIONS_URL: http://traefik:1337/v1/functions
            NHOST_GRAPHQL_URL: http://traefik:1337/v1/graphql
            NHOST_HASURA_URL: http://traefik:1337
            NHOST_JWT_SECRET: '{"type":"HS256", "key": "0f987876650b4a085e64594fae9219e7781b17506bec02489ad061fba8cb22db"}'
            NHOST_REGION: ""
            NHOST_STORAGE_URL: http://traefik:1337/v1/storage
            NHOST_SUBDOMAIN: localhost
            NHOST_WEBHOOK_SECRET: nhost-webhook-secret
        expose:
            - "3000"
        extra_hosts:
            - host.docker.internal:host-gateway
        healthcheck:
            test:
                - CMD-SHELL
                - wget http://localhost:3000/healthz -q -O - > /dev/null 2>&1
            interval: 1s
            start_period: 30m0s
        image: nhost/functions:0.1.8
        labels:
            traefik.enable: "true"
            traefik.http.middlewares.functions-cors.headers.accessControlAllowHeaders: origin,Accept,Authorization,Content-Type
            traefik.http.middlewares.functions-cors.headers.accessControlAllowOriginList: '*'
            traefik.http.middlewares.strip-functions.stripprefix.prefixes: /v1/functions
            traefik.http.routers.functions.entrypoints: web
            traefik.http.routers.functions.middlewares: functions-cors@docker,strip-functions@docker
            traefik.http.routers.functions.rule: PathPrefix(`/v1/functions`)
        restart: always
        volumes:
            - type: bind
              source: ..
              target: /opt/project
            - type: volume
              source: root_node_modules
              target: /opt/project/node_modules
            - type: volume
              source: functions_node_modules
              target: /opt/project/functions/node_modules
    graphql:
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            HASURA_GRAPHQL_ADMIN_SECRET: nhost-admin-secret
            HASURA_GRAPHQL_DATABASE_URL: postgres://nhost_hasura@postgres:5432/postgres
            HASURA_GRAPHQL_DEV_MODE: "true"
            HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
            HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS: "true"
            HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
            HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "0f987876650b4a085e64594fae9219e7781b17506bec02489ad061fba8cb22db"}'
            HASURA_GRAPHQL_LOG_LEVEL: debug
            HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: "20"
            HASURA_GRAPHQL_NO_OF_RETRIES: "20"
            HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
            NHOST_ADMIN_SECRET: nhost-admin-secret
            NHOST_AUTH_URL: http://traefik:1337/v1/auth
            NHOST_BACKEND_URL: http://traefik:1337
            NHOST_FUNCTIONS_URL: http://traefik:1337/v1/functions
            NHOST_GRAPHQL_URL: http://traefik:1337/v1/graphql
            NHOST_HASURA_URL: http://traefik:1337
            NHOST_REGION: ""
            NHOST_STORAGE_URL: http://traefik:1337/v1/storage
            NHOST_SUBDOMAIN: localhost
            NHOST_WEBHOOK_SECRET: nhost-webhook-secret
        extra_hosts:
            - host.docker.internal:host-gateway
        image: hasura/graphql-engine:v2.15.2
        labels:
            traefik.enable: "true"
            traefik.http.routers.hasura.entrypoints: web
            traefik.http.routers.hasura.rule: PathPrefix(`/v1/graphql`, `/v2/query`, `/v1/metadata`, `/v1/config`)
        ports:
            - mode: ingress
              target: 8080
              published: "8080"
              protocol: tcp
        restart: always
    mailhog:
        environment:
            SMTP_HOST: mailhog
            SMTP_PASS: password
            SMTP_PORT: "1025"
            SMTP_SECURE: "false"
            SMTP_SENDER: hasura-auth@example.com
            SMTP_USER: user
        extra_hosts:
            - host.docker.internal:host-gateway
        image: mailhog/mailhog
        ports:
            - mode: ingress
              target: 1025
              published: "1025"
              protocol: tcp
            - mode: ingress
              target: 8025
              published: "8025"
              protocol: tcp
        restart: always
        volumes:
            - type: bind
              source: data/main/mailhog
              target: /maildir
    minio:
        command:
            - server
            - /data
            - --address
            - 0.0.0.0:9000
            - --console-address
            - 0.0.0.0:8484
        environment:
            MINIO_ROOT_PASSWORD: minioaccesskey123123
            MINIO_ROOT_USER: minioaccesskey123123
        extra_hosts:
            - host.docker.internal:host-gateway
        image: minio/minio:RELEASE.2022-07-08T00-05-23Z
        ports:
            - mode: ingress
              target: 9000
              published: "9000"
              protocol: tcp
            - mode: ingress
              target: 8484
              protocol: tcp
        restart: always
        volumes:
            - type: bind
              source: data/main/minio
              target: /data
    postgres:
        command:
            - postgres
            - -c
            - config_file=/etc/postgresql.conf
            - -c
            - hba_file=/etc/pg_hba_local.conf
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        extra_hosts:
            - host.docker.internal:host-gateway
        healthcheck:
            test:
                - CMD-SHELL
                - pg_isready -U postgres -d postgres -q
            interval: 3s
            start_period: 2m0s
        image: nhost/postgres:14.5-20230104-1
        ports:
            - mode: ingress
              target: 5432
              published: "5432"
              protocol: tcp
        restart: always
        volumes:
            - type: bind
              source: data/main/db/pgdata
              target: /var/lib/postgresql/data/pgdata
            - type: bind
              source: data/main/db/pg_hba_local.conf
              target: /etc/pg_hba_local.conf
    storage:
        command:
            - serve
        environment:
            API_ROOT_PREFIX: /v1/storage
            BIND: :8576
            DEBUG: "true"
            HASURA_ENDPOINT: http://graphql:8080/v1
            HASURA_GRAPHQL_ADMIN_SECRET: nhost-admin-secret
            HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "0f987876650b4a085e64594fae9219e7781b17506bec02489ad061fba8cb22db"}'
            HASURA_METADATA: "1"
            NHOST_ADMIN_SECRET: nhost-admin-secret
            NHOST_JWT_SECRET: '{"type":"HS256", "key": "0f987876650b4a085e64594fae9219e7781b17506bec02489ad061fba8cb22db"}'
            NHOST_WEBHOOK_SECRET: nhost-webhook-secret
            POSTGRES_MIGRATIONS: "1"
            POSTGRES_MIGRATIONS_SOURCE: postgres://nhost_storage_admin@postgres:5432/postgres?sslmode=disable
            PUBLIC_URL: http://localhost:1337
            S3_ACCESS_KEY: minioaccesskey123123
            S3_BUCKET: nhost
            S3_ENDPOINT: http://minio:9000
            S3_SECRET_KEY: minioaccesskey123123
            STORAGE_FORCE_DOWNLOAD_FOR_CONTENT_TYPES: text/html,application/javascript
        expose:
            - "8576"
        extra_hosts:
            - host.docker.internal:host-gateway
        image: nhost/hasura-storage:0.3.0
        labels:
            traefik.enable: "true"
            traefik.http.routers.storage.entrypoints: web
            traefik.http.routers.storage.rule: PathPrefix(`/v1/storage`)
        restart: always
    traefik:
        command:
            - --api.insecure=true
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --providers.docker.constraints=Label(`com.docker.compose.project`,`rebound-chatbot-xenodochial_hoover`)
            - --entrypoints.web.address=:1337
        extra_hosts:
            - host.docker.internal:host-gateway
        image: traefik:v2.8
        ports:
            - mode: ingress
              target: 1337
              published: "1337"
              protocol: tcp
            - mode: ingress
              target: 8080
              protocol: tcp
        restart: always
        volumes:
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
              read_only: true
volumes:
    functions_node_modules: {}
    root_node_modules: {}
